<?php
use Extended\ACF\Fields\Select;
use Extended\ACF\Location;

$fields = register_extended_field_group([
    'title' => 'Project Details',
    'fields' => [
        Select::make('Country', 'country')
            ->choices([
                ''  => 'Select a country',
                'AF' => 'Afghanistan',
                'AL' => 'Albania',
                'DZ' => 'Algeria',
                'AR' => 'Argentina',
                'AU' => 'Australia',
                'AT' => 'Austria',
                'BD' => 'Bangladesh',
                'BE' => 'Belgium',
                'BR' => 'Brazil',
                'BG' => 'Bulgaria',
                'CA' => 'Canada',
                'CN' => 'China',
                'CO' => 'Colombia',
                'HR' => 'Croatia',
                'CZ' => 'Czech Republic',
                'DK' => 'Denmark',
                'EG' => 'Egypt',
                'EE' => 'Estonia',
                'FI' => 'Finland',
                'FR' => 'France',
                'DE' => 'Germany',
                'GR' => 'Greece',
                'HK' => 'Hong Kong',
                'HU' => 'Hungary',
                'IN' => 'India',
                'ID' => 'Indonesia',
                'IE' => 'Ireland',
                'IL' => 'Israel',
                'IT' => 'Italy',
                'JP' => 'Japan',
                'KE' => 'Kenya',
                'KW' => 'Kuwait',
                'MY' => 'Malaysia',
                'MX' => 'Mexico',
                'MA' => 'Morocco',
                'NP' => 'Nepal',
                'NL' => 'Netherlands',
                'NZ' => 'New Zealand',
                'NG' => 'Nigeria',
                'NO' => 'Norway',
                'PK' => 'Pakistan',
                'PE' => 'Peru',
                'PH' => 'Philippines',
                'PL' => 'Poland',
                'PT' => 'Portugal',
                'QA' => 'Qatar',
                'RO' => 'Romania',
                'SA' => 'Saudi Arabia',
                'SG' => 'Singapore',
                'ZA' => 'South Africa',
                'KR' => 'South Korea',
                'ES' => 'Spain',
                'SE' => 'Sweden',
                'CH' => 'Switzerland',
                'TW' => 'Taiwan',
                'TH' => 'Thailand',
                'TR' => 'Turkey',
                'UA' => 'Ukraine',
                'AE' => 'United Arab Emirates',
                'GB' => 'United Kingdom',
                'US' => 'United States',
                'VN' => 'Vietnam',
            ])
            ->format('array'),
    ],

    'location' => [
        Location::where('post_type', 'projects'),
    ],
]);
